
!
! No configuration change since last restart
! NVRAM config last updated at 16:48:35 UTC Wed May 13 2026
!
version 15.7
service timestamps debug datetime msec
service timestamps log datetime msec
no service password-encryption
!
hostname ISP-2
!
boot-start-marker
boot-end-marker
!
!
!
no aaa new-model
!
!
!
mmi polling-interval 60
no mmi auto-configure
no mmi pvc
mmi snmp-timeout 180
!
!
!
!
!
!
!
!
!
!
!
!
!
!
!


!
!
!
!
ip cef
no ipv6 cef
!
multilink bundle-name authenticated
!
!
!
!
!
!
!
!
!
!
redundancy
!
!
! 
!
!
!
!
!
!
!
!
!
!
!
!
interface Ethernet0/0
 no shutdown
 ip address dhcp
 duplex auto
!
interface Ethernet0/1
 no shutdown
 no ip address
 shutdown
 duplex auto
!
interface Ethernet0/2
 no shutdown
 no ip address
 shutdown
 duplex auto
!
interface Ethernet0/3
 no shutdown
 no ip address
 shutdown
 duplex auto
!
interface Serial1/0
 no shutdown
 ip address 198.51.100.1 255.255.255.252
 serial restart-delay 0
!
interface Serial1/1
 no shutdown
 no ip address
 shutdown
 serial restart-delay 0
!
interface Serial1/2
 no shutdown
 no ip address
 shutdown
 serial restart-delay 0
!
interface Serial1/3
 no shutdown
 no ip address
 shutdown
 serial restart-delay 0
!
ip forward-protocol nd
!
!
no ip http server
no ip http secure-server
ip route 10.255.0.12 255.255.255.252 198.51.100.2
ip route 0.0.0.0 0.0.0.0 dhcp
!
ipv6 ioam timestamp
!
!
!
control-plane
!
!
!
!
!
!
!
!
line con 0
 logging synchronous
line aux 0
line vty 0 4
 login
 transport input none
!
ntp server 34.202.215.187
ntp server pool.ntp.org
!
end
